name: pyvdms 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - scipy
  - obspy>=1.2.0
  - pandas
  - matplotlib
  - basemap
  - cartopy
  - dateparser
  - humanfriendly
  - tabulate
  - pip
  - pip:
    - python-crontab
